CFProject/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CFProject.Models;
using Microsoft.AspNetCore.Http;

namespace CFProject.Controllers
{
    public class AdminController : Controller
    {
        private readonly TaskContext _context;

        public AdminController(TaskContext context)
        {
            _context = context;
        }

        // GET: Admin
        public IActionResult Index()
        {
            var taskContext = _context.UserTask.Include(u => u.Project).Include(u => u.User).Include(u => u.Project.Company).ToList();
            return View(taskContext);
        }

        public IActionResult Search()
        {
            string searchTerm = Request.Form["SearchTerm"];
            var searchResults = from p in _context.UserTask.Include(b => b.Project).Include(p => p.User) 
                                where p.Project.Title.Contains(searchTerm) 
                                select p;
            return View("Index", searchResults.ToList());
        }

        
        // GET: Admin/Create
        public IActionResult Create()
        {
            ViewData["TaskId"] = new SelectList(_context.Project, "TaskId", "Title");
            ViewData["UserId"] = new SelectList(_context.User, "UserId", "Name");
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,TaskId")] UserTask userTask)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(userTask);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["TaskId"] = new SelectList(_context.Project, "TaskId", "Title", userTask.TaskId);
                ViewData["UserId"] = new SelectList(_context.User, "UserId", "Name", userTask.UserId);
                return View(userTask);
            }
            catch
            {
                TempData["Create"] = "Error";
                return View(userTask);
            }
            
        }



        // GET: Admin/Delete/5
       
        public IActionResult GoToDelete(int? userId, int? taskId)
        {
            if(TempData["TaskId"] != null)
            {
                taskId = (int)TempData["TaskId"];
            }

            var userTask = _context.UserTask
                .Include(u => u.Project)
                .Include(u => u.User)
                .Where(u => u.TaskId == taskId);

            if (userTask == null)
            {
                return NotFound();
            }

            return View("Delete", userTask.ToList());
        }


        // POST: Admin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete()
        {
            int taskId = Convert.ToInt32(Request.Form["TaskId"]);

            var deleteAll = from d in _context.UserTask 
                            where d.TaskId == taskId 
                            select d;

            foreach(var project in deleteAll)
            {
                _context.UserTask.Remove(project);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveFromTask()
        {
            int userId = Convert.ToInt32(Request.Form["UserId"]);
            int taskId = Convert.ToInt32(Request.Form["TaskId"]);

            var connection = _context.UserTask.Find(userId, taskId);
            if(connection == null)
            {
                TempData["RemoveConnection"] = "NotFound";
                return View("Delete");
            }

            _context.UserTask.Remove(connection);
            User user = _context.User.Find(userId);
            TempData["Username"] = user.Name;
            _context.SaveChanges();
            TempData["RemoveConnection"] = "Success";
            TempData["TaskId"] = taskId;
            return RedirectToAction("GoToDelete");
        }

        private bool UserTaskExists(int id)
        {
            return _context.UserTask.Any(e => e.UserId == id);
        }
    }
}

CFProject/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CFProject.Models;
using Microsoft.AspNetCore.Http;

namespace CFProject.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly TaskContext _context;

        public ProjectsController(TaskContext context)
        {
            _context = context;
        }

        // GET: Projects
        public IActionResult Index()
        {
            var taskContext = _context.UserTask.Include(p => p.Project).Include(p => p.Project.Company).Include(p => p.User);
            
            return View(taskContext.ToList());
        }

        public IActionResult Search()
        {
            string searchTerm = Request.Form["SearchTerm"];
            var searchResults = from p in _context.UserTask.Include(b => b.Project).Include(p => p.Project.Company).Include(p => p.User) 
                                where p.Project.Title.Contains(searchTerm) 
                                select p;
            return View("Index", searchResults.ToList());
        }

        // GET: Projects/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = _context.UserTask
                .Include(p => p.Project)
                .Include(p => p.Project.Company)
                .Include(p => p.User);
            if (project == null)
            {
                return NotFound();
            }
            TempData["ProjectId"] = id;
            return View(project.ToList());
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TaskId,Title,Description,CompanyId")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "Name", project.CompanyId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "Name", project.CompanyId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TaskId,Title,Description,CompanyId")] Project project)
        {
            if (id != project.TaskId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.TaskId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "Name", project.CompanyId);
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .Include(p => p.Company)
                .FirstOrDefaultAsync(m => m.TaskId == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Project.FindAsync(id);
            _context.Project.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Project.Any(e => e.TaskId == id);
        }
    }
}

CFProject/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CFProject.Models;

namespace CFProject.Controllers
{
    public class UsersController : Controller
    {
        private readonly TaskContext _context;

        public UsersController(TaskContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var taskContext = _context.User.Include(u => u.Manager).Include(u => u.Role);
            return View(await taskContext.ToListAsync());
        }

        public IActionResult Search()
        {
            string searchTerm = Request.Form["SearchTerm"];
            var searchResults = from u in _context.User.Include(u => u.Manager).Include(u => u.Role)
                                where u.Name.Contains(searchTerm)
                                select u;
            return View("Index", searchResults);
        }


        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .Include(u => u.Manager)
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            //Get all managers
            var managers = from m in _context.User.Include(m => m.Manager).Include(m => m.Role) where m.RoleId > 1 select m;

            List<SelectListItem> items = new SelectList(managers, "UserId", "Name").ToList();
            items.Insert(0, (new SelectListItem { Text = "[None]", Value = "0" }));

            ViewData["ManagerId"] = items;
            ViewData["RoleId"] = new SelectList(_context.Role, "RoleId", "RoleName");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Name,Password,ManagerId,RoleId")] User user)
        {
            if (ModelState.IsValid)
            {
                if (user.ManagerId == 0)
                {
                    user.Manager = null;
                    user.ManagerId = null;
                }
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManagerId"] = new SelectList(_context.User, "UserId", "Name", user.ManagerId);
            ViewData["RoleId"] = new SelectList(_context.Role, "RoleId", "RoleName", user.RoleId);
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["ManagerId"] = new SelectList(_context.User, "UserId", "Name", user.ManagerId);
            ViewData["RoleId"] = new SelectList(_context.Role, "RoleId", "RoleName", user.RoleId);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Name,Password,ManagerId,RoleId")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManagerId"] = new SelectList(_context.User, "UserId", "Name", user.ManagerId);
            ViewData["RoleId"] = new SelectList(_context.Role, "RoleId", "RoleName", user.RoleId);
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .Include(u => u.Manager)
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.UserId == id);
        }
    }
}

CFProject/Views/Admin/Create.cshtml
@model CFProject.Models.UserTask

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UserTask</h4>
<hr />

@if (TempData["Create"] != null && (string)TempData["Create"] == "Error")
{
    <div class="alert alert-success">
        This user is already assigned to this task
    </div>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TaskId" class="control-label"></label>
                <select asp-for="TaskId" class="form-control" asp-items="ViewBag.TaskId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CFProject/Views/Admin/Delete.cshtml
@model IEnumerable<CFProject.Models.UserTask>

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

@{
    List<int> existingTasks = new List<int>();
}
@foreach (var project in Model)
{
    if (!existingTasks.Contains(project.TaskId))
    {
        existingTasks.Add(project.TaskId);


        <h3>Are you sure you want to delete this?</h3>
        <div class="d-flex">
            <div class="w-50 m-2">
                <hr />
                <h2>@project.Project.Title</h2>
                <h5>Description</h5>
                <p>@project.Project.Description</p>
            </div>
            <div class="w-50 m-2">
                <h4 class="text-center">
                    Remove a programmer
                </h4>
                @switch (TempData["RemoveConnection"])
                {
                    case "Success":
                        <div class="alert alert-success">
                            @TempData["Username"] has been removed
                        </div>
                        break;

                    case "NotFound":
                        <div class="alert alert-danger">
                            An error occured. Try again later
                        </div>
                        break;
                }
                @foreach (var programmer in Model)
                {
                    <div class="d-flex">
                        <div class="w-50">
                            <h5 class="text-center">@programmer.User.Name</h5>
                        </div>
                        <div class="w-50">
                            <form asp-action="RemoveFromTask" asp-controller="Admin">
                                <input type="hidden" name="UserId" value="@programmer.UserId" />
                                <input type="hidden" name="TaskId" value="@programmer.TaskId" />
                                <button class="btn btn-outline-danger" type="submit">Remove</button>
                            </form>

                        </div>


                    </div>

                }
            </div>
        </div>


        <form asp-action="Delete">
            <input type="hidden" name="TaskId" value="@project.TaskId" />
            <button type="submit" class="btn btn-danger">Delete all connections</button> |
        </form>
        <a class="btn btn-outline-info" asp-action="Index">Back to List</a>


    }
}

CFProject/Views/Admin/Details.cshtml
@model CFProject.Models.UserTask

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UserTask</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Title)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

CFProject/Views/Admin/Edit.cshtml
@model CFProject.Models.UserTask

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" />
            <input type="hidden" asp-for="TaskId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CFProject/Views/Admin/Index.cshtml
@model IEnumerable<CFProject.Models.UserTask>

@{
    ViewData["Title"] = "Index";
}


<h1>Index</h1>

<div>

    <div class="btn btn-outline-info ">
        <a class="text-info text-decoration-none" asp-action="Create" asp-controller="Users">Create New Programmer</a>
    </div>

    <div class="btn btn-outline-info">
        <a class="text-info text-decoration-none" asp-action="Create" asp-controller="Projects">Create New Project</a>
    </div>

    <div class="btn btn-outline-primary">
        <a class="text-Primary text-decoration-none" asp-action="Create" asp-controller="Admin">Asign programmer to project</a>
    </div>

    <div>
        <table class="table">
            <thead>
                <tr>
                    <td>
                        @Html.DisplayNameFor(modelItem => modelItem.Project.Title)
                    </td>
                    <td class="w-50">
                        @Html.DisplayNameFor(modelItem => modelItem.Project.Description)
                    </td>
                    <td>
                        Company
                    </td>
                    <td>
                        Assigned Programmers
                    </td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @{
                    List<int> existingTasks = new List<int>();
                }
                @foreach (var item in Model)
                {
                    if (!existingTasks.Contains(item.TaskId))
                    {
                        existingTasks.Add(item.TaskId);
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Project.Title)
                            </td>
                            <td class="w-50">
                                @Html.DisplayFor(modelItem => item.Project.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Project.Company.Name)
                            </td>
                            <td>

                                <ul class="list-unstyled m-0 p-0">
                                    @foreach (var programmer in Model)
                                    {
                                        if (programmer.TaskId == item.TaskId)
                                        {
                                            <li>
                                                @programmer.User.Name
                                            </li>
                                        }
                                    }
                                </ul>

                            </td>
                            <td>
                                <form asp-action="GoToDelete" asp-controller="Admin">
                                        <input type="hidden" name="TaskId" value="@item.TaskId" />
                                        <input type="hidden" name="UserId" value="@item.UserId" />
                                        <button class="btn btn-outline-danger" type="submit">Delete</button>
                                    </form>
                            </td>
                        </tr>
                    }

                }
            </tbody>
        </table>



    </div>
</div>